[ClassVersion("1.0"), FriendlyName("xPfxImport")]
class MSFT_xPfxImport : OMI_BaseResource
{
    [Key,Description("The thumbprint (unique identifier) of the PFX file you're importing.")] string Thumbprint;
    [Required,Description("The path to the PFX file you want to import.")] string Path;
    [Key,Description("The Windows Certificate Store Location to import the PFX file to."),ValueMap{"LocalMachine", "CurrentUser"},Values{"LocalMachine", "CurrentUser"}] string Location;
    [Key,Description("The Windows Certificate Store Name to import the PFX file to.")] string Store;
    [write,Description("Determines whether the private key is exportable from the machine after it has been imported")] boolean Exportable;
    [write,Description("A [PSCredential] object that is used to decrypt the PFX file."),EmbeddedInstance("MSFT_Credential")] string Credential;
    [Write,Description("Specifies whether the PFX file should be present or absent."),ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};
